metadata:
  repository: dianemo/rootfs
  variables:
    rootfs: /rootfs
    srcCRITools: https://github.com/kubernetes-incubator/cri-tools/releases/download/v1.11.1/crictl-v1.11.1-linux-amd64.tar.gz
    srcDocker: https://download.docker.com/linux/static/stable/x86_64/docker-17.03.2-ce.tgz
    srcKubeadm: https://storage.googleapis.com/kubernetes-release/release/v1.11.1/bin/linux/amd64/kubeadm
pipeline:
  stages:
  - image
stages:
  image:
    tasks:
    - base
    - certs
    - crictl
    - docker
    - kubeadm
    - cleanup
    - rootfs
tasks:
  certs:
    template: |
      RUN mkdir -p {{ index .Variables "rootfs" }}/etc/ssl/certs
      RUN curl -o {{ index .Variables "rootfs" }}/etc/ssl/certs/ca-certificates.crt https://curl.haxx.se/ca/cacert.pem
  cleanup:
    template: |
      COPY src/cleanup.sh /tools/bin
      RUN chmod +x /tools/bin/cleanup.sh
      RUN /tools/bin/cleanup.sh {{ index .Variables "rootfs" }}
  crictl:
    template: |
      RUN curl -L {{ index .Variables "srcCRITools" }} | tar -xz -C {{ index .Variables "rootfs" }}/bin
  docker:
    template: |
      RUN curl -L {{ index .Variables "srcDocker" }} | tar --strip-components=1 -xz -C {{ index .Variables "rootfs" }}/bin
  base:
    template: |
      FROM dianemo/tools:{{ .Docker.Image.Tag }} AS {{ .Docker.CurrentStage }}
      ENV PATH $PATH:/tools/bin
      WORKDIR {{ index .Variables "rootfs" }}
      COPY src/fsh.sh /tools/bin
      RUN chmod +x /tools/bin/fsh.sh
      RUN fsh.sh {{ index .Variables "rootfs" }}
  kubeadm:
    template: |
      RUN curl --retry 3 --retry-delay 60 -L {{ index .Variables "srcKubeadm" }} -o {{ index .Variables "rootfs" }}/bin/kubeadm
      RUN chmod +x {{ index .Variables "rootfs" }}/bin/kubeadm
  rootfs:
    template: |
      FROM scratch
      LABEL maintainer="Andrew Rynhard <andrew.rynhard@autonomy.io>"
      COPY --from=base {{ index .Variables "rootfs" }} {{ index .Variables "rootfs" }}
