metadata:
  repository: dianemo/rootfs
  variables:
    rootfs: /rootfs
    srcContainerd: https://github.com/containerd/containerd/releases/download/v1.2.0/containerd-1.2.0.linux-amd64.tar.gz
    srcCRITools: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.12.0/crictl-v1.12.0-linux-amd64.tar.gz
    srcLibseccomp: https://github.com/seccomp/libseccomp/releases/download/v2.3.3/libseccomp-2.3.3.tar.gz
    srcKubeadm: https://storage.googleapis.com/kubernetes-release/release/v1.13.0-alpha.3/bin/linux/amd64/kubeadm
    srcRunc: https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64
pipeline:
  stages:
  - image
stages:
  image:
    tasks:
    - libseccomp
    - libblkid
    - libuuid
    - certs
    - crictl
    - containerd
    - runc
    - kubeadm
    - cleanup
    - rootfs
tasks:
  certs:
    template: |
      RUN mkdir -p {{ index .Variables "rootfs" }}/etc/ssl/certs
      RUN curl -o {{ index .Variables "rootfs" }}/etc/ssl/certs/ca-certificates.crt https://curl.haxx.se/ca/cacert.pem
  cleanup:
    template: |
      COPY src/cleanup.sh /tools/bin
      RUN chmod +x /tools/bin/cleanup.sh
      RUN /tools/bin/cleanup.sh {{ index .Variables "rootfs" }}
  containerd:
    template: |
      RUN curl -L {{ index .Variables "srcContainerd" }} | tar --strip-components=1 -xz -C {{ index .Variables "rootfs" }}/bin
      RUN rm {{ index .Variables "rootfs" }}/bin/ctr
  crictl:
    template: |
      RUN curl -L {{ index .Variables "srcCRITools" }} | tar -xz -C {{ index .Variables "rootfs" }}/bin
  libblkid:
    template: |
      RUN cp /tools/lib/libblkid.* {{ index .Variables "rootfs" }}/lib
  libuuid:
    template: |
      RUN cp /tools/lib/libuuid.* {{ index .Variables "rootfs" }}/lib
  libseccomp:
    template: |
      FROM dianemo/tools:{{ .Docker.Image.Tag }} AS {{ .Docker.CurrentStage }}
      WORKDIR /tools/usr/local/src/{{ .Docker.CurrentStage }}
      RUN curl -L {{index .Variables "srcLibseccomp" }} | tar --strip-components=1 -xz
      WORKDIR build
      RUN ../configure \
            --prefix=/usr \
            --disable-static
      RUN make -j $(($(nproc) / 2))
      RUN make install DESTDIR={{ index .Variables "rootfs" }}
  kubeadm:
    template: |
      RUN curl --retry 3 --retry-delay 60 -L {{ index .Variables "srcKubeadm" }} -o {{ index .Variables "rootfs" }}/bin/kubeadm
      RUN chmod +x {{ index .Variables "rootfs" }}/bin/kubeadm
  rootfs:
    template: |
      FROM scratch
      LABEL maintainer="Andrew Rynhard <andrew.rynhard@autonomy.io>"
      COPY --from=libseccomp {{ index .Variables "rootfs" }} {{ index .Variables "rootfs" }}
  runc:
    template: |
      RUN curl -L {{ index .Variables "srcRunc" }} -o {{ index .Variables "rootfs" }}/bin/runc
      RUN chmod +x {{ index .Variables "rootfs" }}/bin/runc
