metadata:
  repository: talos/kernel
  variables:
    artifacts: /artifacts
    runcCheckConfig: https://raw.githubusercontent.com/opencontainers/runc/v1.0.0-rc5/script/check-config.sh
    srcLinux: https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.1.tar.xz
pipeline:
  stages:
  - build
stages:
  build:
    tasks:
    - linux
tasks:
  linux:
    template: |
      FROM talos/tools:{{ .Docker.Image.Tag}} AS {{ .Docker.CurrentStage }}
      WORKDIR /tools/usr/local/src/{{ .Docker.CurrentStage }}
      RUN curl -L {{ index .Variables "srcLinux" }} | tar --strip-components=1 -xJ
      ADD {{ index .Variables "runcCheckConfig" }} /bin/check-config.sh
      RUN chmod +x /bin/check-config.sh
      RUN make mrproper
      COPY src/linux/config .config
      RUN mkdir -p /usr/bin \
          && ln -s /tools/bin/env /usr/bin/env \
          && ln -s /tools/bin/true /bin/true \
          && ln -s /tools/bin/pwd /bin/pwd
      RUN check-config.sh .config
      RUN unlink /lib
      RUN ln -s /tools/lib /lib
      RUN make -j $(($(nproc) / 2))
      RUN cp arch/x86/boot/bzImage /tmp/vmlinuz
      FROM scratch
      COPY --from={{ .Docker.CurrentStage }} /tmp /tmp
