metadata:
  repository: autonomy/dianemo
policies:
- type: conventionalCommit
  spec:
    types:
    - chore
    - docs
    - perf
    - refactor
    - style
    - test
    scopes:
    - image
    - init
    - initramfs
    - kernel
    - osctl
    - osd
    - rootfs
    - tools
    - '*'
script:
  template: |
    #!/bin/sh

    set -e

    mkdir -p ./build
    rm -rf ./build/*
    cd tools && conform enforce
    cd ../kernel && conform enforce
    cd ../initramfs && conform enforce
    cd ../rootfs && conform enforce
    cd ../image && conform enforce
    cd ../
