metadata:
  repository: autonomy/talos
policies:
- type: conventionalCommit
  spec:
    types:
    - chore
    - docs
    - perf
    - refactor
    - style
    - test
    scopes:
    - ami
    - ci
    - conformance
    - hack
    - image
    - init
    - initramfs
    - kernel
    - osctl
    - osd
    - rootfs
    - tools
    - '*'
script:
  template: |
    #!/bin/sh

    set -e

    mkdir -p ./build
    cd ./src/tools && conform build
    cd ../kernel && conform build
    cd ../rootfs && conform build
    cd ../initramfs && conform build
    cd ../image && conform build
    cd ../docs && conform build
    cd ../
