policies:
- type: commit
  spec:
    headerLength: 89
    dco: true
    gpg: false
    imperative: true
    conventional:
      types:
      - chore
      - docs
      - perf
      - refactor
      - style
      - test
      scopes:
      - ami
      - ci
      - conformance
      - gpt
      - hack
      - image
      - init
      - initramfs
      - kernel
      - osctl
      - osd
      - osinstall
      - rootfs
      - tools
      - '*'
- type: license
  spec:
    includeSuffixes:
    - .go
    headerFile: LICENSE_HEADER
