policies:
- type: conventionalCommit
  spec:
    types:
    - chore
    - docs
    - perf
    - refactor
    - style
    - test
    scopes:
    - ami
    - ci
    - conformance
    - gpt
    - hack
    - image
    - init
    - initramfs
    - kernel
    - osctl
    - osd
    - rootfs
    - tools
    - '*'
