policies:
- type: commit
  spec:
    headerLength: 89
    dco: true
    gpg: true
- type: conventionalCommit
  spec:
    types:
    - chore
    - docs
    - perf
    - refactor
    - style
    - test
    scopes:
    - ami
    - ci
    - conformance
    - gpt
    - hack
    - image
    - init
    - initramfs
    - kernel
    - osctl
    - osd
    - rootfs
    - tools
    - '*'
- type: license
  spec:
    includeSuffixes:
    - .go
    headerFile: LICENSE_HEADER
