metadata:
  repository: dianemo/build
policies:
- type: conventionalCommit
  spec:
    types:
    - chore
    - docs
    - perf
    - refactor
    - style
    - test
    scopes:
    - generate
    - init
    - initramfs
    - kernel
    - osctl
    - osd
    - rootfs
    - tools
    - '*'
script:
  template: |
    #!/bin/sh

    set -e

    mkdir -p ./build
    rm -rf ./build/*

    cd tools && conform enforce
    cd ../kernel && conform enforce
    cd ../initramfs && conform enforce
    cd ../rootfs && conform enforce
    cd ../generate && conform enforce
    cd ../

    {{ if and .Git.IsClean .Git.IsTag }}
    packer build -var 'version={{ .Git.Tag }}' packer.json
    {{ else if and .Git.IsClean (eq .Git.Branch "master") }}
    packer build -var 'version={{ .Git.SHA }}' packer.json
    {{ end }}
