metadata:
  repository: dianemo/build
policies:
- type: conventionalCommit
  spec:
    types:
    - chore
    - docs
    - perf
    - refactor
    - style
    - test
    scopes:
    - generate
    - init
    - initramfs
    - kernel
    - osctl
    - osd
    - rootfs
    - tools
    - '*'
script:
  template: |
    #!/bin/sh

    set -e

    cd tools && conform enforce
    cd ../kernel && conform enforce
    cd ../initramfs && conform enforce
    cd ../rootfs && conform enforce
    cd ../generate && conform enforce
    cd ../

    {{ if or (and .Git.IsClean .Git.IsTag) (and .Git.IsClean (eq .Git.Branch "master")) }}
    packer build -var 'version={{ .Docker.Image.Tag }}' packer.json
    {{ end }}
