kind: pipeline
name: default

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags
  when:
    event: tag

- name: conform
  image: autonomy/conform:c539351
  depends_on:
  - fetch

- name: lint
  image: autonomy/build-container:latest
  pull: always
  environment:
    BUILDKIT_HOST: tcp://buildkitd.ci.svc:1234
  commands:
    - make lint
  volumes:
  - name: dockersock
    path: /var/run
  depends_on:
  - fetch

- name: test
  image: autonomy/build-container:latest
  pull: always
  environment:
    BUILDKIT_HOST: tcp://buildkitd.ci.svc:1234
  commands:
    - make test
  volumes:
  - name: dockersock
    path: /var/run
  depends_on:
  - fetch

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
     - coverage.txt
  depends_on:
  - test

- name: build
  image: autonomy/build-container:latest
  pull: always
  environment:
    BUILDKIT_HOST: tcp://buildkitd.ci.svc:1234
  commands:
    - make clean
    - make
  depends_on:
  - fetch
  volumes:
  - name: dockersock
    path: /var/run
  depends_on:
  - fetch
  - test

- name: basic-integration
  image: autonomy/build-container:latest
  pull: always
  environment:
    BUILDKIT_HOST: tcp://buildkitd.ci.svc:1234
  commands:
    - cd hack/dev
    - make integration
  volumes:
  - name: dockersock
    path: /var/run
  depends_on:
  - build
  when:
    event: pull_request

- name: push
  image: autonomy/build-container:latest
  pull: always
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - make login
  - make push
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
      exclude:
      - pull_request
  depends_on:
  - basic-integration

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    draft: true
    note: CHANGELOG.md
    files:
    - build/*
    checksum:
    - sha256
    - sha512
  when:
    event: tag
  depends_on:
  - basic-integration

volumes:
- name: dockersock
  temp: {}
