version: '3.7'

services:
  os1:
    image: ${IMAGE:-autonomy/talos-os}:${TAG}
    privileged: true
    security_opt:
      - seccomp:unconfined
    entrypoint: /sbin/init
    command: --switch-root
    volumes:
      # logging hacks
      - ./os1.kmsg:/dev/kmsg
      - ./os1.logs/:/var/log/
      # os config
      - ./config/${NODE:-talos-os-1}.yaml:/run/userdata.yaml
      # state dirs
      - os1_containerd:/var/lib/containerd/
      - os1_etcd:/var/lib/etcd/
      - os1_kubelet:/var/lib/kubelet/
      - os1_kubernetes:/etc/kubernetes/
      # kubeadm mounts os-release, but init --switch-root does not create
      - ./os-release:/etc/os-release
      # kubelet is missing cni mount
      - os1_cni:/etc/cni/
    tmpfs:
      - /run
    # sysctls:
    #   net.bridge.bridge-nf-call-iptables: 1
    #   # this proc sysctl path is missing in the container
    #   # kubeadm errors on pre-flight -- modified init to ignore it
    ports:
      - "50000:50000" # osd
      - "6443:6443" # kube-api-server

volumes:
  os1_containerd:
  os1_etcd:
  os1_kubelet:
  os1_kubernetes:
  os1_ssl:
  os1_cni:
