metadata:
  repository: dianemo/generate
  variables:
    cmd: "raw"
    srcSyslinux: https://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.xz
policies:
- type: conventionalCommit
  spec:
    types:
    - chore
    - docs
    - perf
    - refactor
    - style
    - test
    scopes:
    - '*'
script:
  template: |
    mkdir -p ../build
    docker run --rm -v $PWD/../build:/out -v /dev:/dev --privileged {{ .Docker.Image.Name }}:{{ .Docker.Image.Tag }} {{ index .Variables "cmd" }}
pipeline:
  stages:
  - generate
stages:
  generate:
    tasks:
    - generate
  test:
    tasks:
    - test
tasks:
  generate:
    template: |
      FROM alpine:3.7
      RUN apk --update add curl e2fsprogs tar cdrkit parted syslinux util-linux xfsprogs xz sgdisk sfdisk qemu-img
      WORKDIR /usr/local/src/syslinux
      RUN curl -L {{ index .Variables "srcSyslinux" }} | tar --strip-components=1 -xJ
      COPY src/entrypoint.sh /bin/entrypoint.sh
      RUN chmod +x /bin/entrypoint.sh
      COPY --from=dianemo/rootfs:{{ .Docker.Image.Tag }} /rootfs /rootfs
      COPY --from=dianemo/kernel:{{ .Docker.Image.Tag }} /tmp/vmlinuz /rootfs/boot/vmlinuz
      COPY --from=dianemo/kernel:{{ .Docker.Image.Tag }} /tmp/lib/modules /rootfs/lib/modules
      COPY --from=dianemo/initramfs:{{ .Docker.Image.Tag }} /tmp/initramfs.xz /rootfs/boot/initramfs.xz
      COPY --from=dianemo/initramfs:{{ .Docker.Image.Tag }} /tmp/init /rootfs/bin/init
      WORKDIR /rootfs
      ENTRYPOINT ["entrypoint.sh"]
