metadata:
  repository: dianemo/initramfs
pipeline:
  stages:
  - generate
  - build
stages:
  build:
    artifacts:
    - source: /tmp/cli
      destination: ../build/osctl
    tasks:
    - test
    - cli
    - init
  generate:
    artifacts:
    - source: /go/src/github.com/autonomy/dianemo/proto
      destination: ./src/init
    tasks:
    - proto
tasks:
  cli:
    template: |
      FROM dianemo/tools:{{ .Docker.Image.Tag }} AS {{ .Docker.CurrentStage }}
      RUN ln -s /tools/lib64 /lib64
      RUN mkdir /tmp
      WORKDIR $GOPATH/src/github.com/autonomy/dianemo/initramfs/src/init
      COPY src/init ./
      WORKDIR $GOPATH/src/github.com/autonomy/dianemo/initramfs/src/init/cli
      RUN GOOS=darwin go build -o /cli
      RUN chmod +x /cli
  init:
    template: |
      FROM dianemo/tools:{{ .Docker.Image.Tag }} AS {{ .Docker.CurrentStage }}
      RUN ln -s /tools/lib64 /lib64
      RUN mkdir /tmp
      WORKDIR $GOPATH/src/github.com/autonomy/dianemo/initramfs/src/init
      COPY src/init ./
      RUN go build -ldflags '-s -w -linkmode external -extldflags "-static -L/usr/lib -lblkid -luuid"' -o /initramfs/init
      RUN chmod +x /initramfs/init
      WORKDIR /initramfs
      RUN find . 2>/dev/null | cpio -H newc -o | xz -v -C crc32 -9 -e -T 0 -z >/initramfs/initramfs.xz
      FROM scratch
      WORKDIR /tmp
      COPY --from=init /initramfs/init init
      COPY --from=init /initramfs/initramfs.xz initramfs.xz
      COPY --from=cli /cli cli
      CMD false
  proto:
    template: |
      FROM golang:1.10.0 AS {{ .Docker.CurrentStage }}
      WORKDIR /go/src/github.com/autonomy/dianemo
      RUN apt-get update
      RUN apt-get -y install bsdtar
      RUN go get github.com/golang/protobuf/protoc-gen-go
      RUN curl -L https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip | bsdtar -xf -  -C /tmp \
          && mv /tmp/bin/protoc /bin \
          && mv /tmp/include/* /usr/local/include \
          && chmod +x /bin/protoc
      COPY ./src/init/proto ./proto
      RUN protoc -I/usr/local/include -I./proto --go_out=plugins=grpc:proto proto/api.proto
  test:
    template: |
      FROM dianemo/tools:{{ .Docker.Image.Tag }} AS {{ .Docker.CurrentStage }}
      RUN ln -s /tools/lib64 /lib64
      RUN mkdir /tmp
      RUN curl -L https://github.com/alecthomas/gometalinter/releases/download/v2.0.5/gometalinter-2.0.5-linux-amd64.tar.gz | tar -xz --strip-components=1 -C /tools/bin
      WORKDIR $GOPATH/src/github.com/autonomy/dianemo/initramfs/src/init
      COPY src/init ./
      COPY --from=autonomy/golang:1.10 /bin/test.sh /bin/test.sh
      RUN test.sh
