baseURL = "https://dianemo.autonomy.io/"
languageCode = "en-us"
title = "Dianemo"
theme = "autonomy"

[params]
    Copyright = "Released under Mozilla Public License 2.0"
    GitHubLink = "https://github.com/autonomy/dianemo"

[[menu.main]]
    identifier = "components"
    name       = "Components"
    url        = "/components/"
    weight     = 10

[[menu.main]]
    identifier = "configuration"
    name       = "Configuration"
    url        = "/configuration/"
    weight     = 20

[[menu.main]]
    identifier = "examples"
    name       = "Examples"
    url        = "/examples/"
    weight     = 30
