apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  # nodeSelector:
  #   kubernetes.io/hostname: ${HOSTNAME}
  tolerations:
  - operator: Exists
  containers:
    - name: debug
      image: ubuntu:18.04
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      env:
      - name: DOCKER_HOST
        value: unix:///rootfs/run/docker.sock
      volumeMounts:
      - mountPath: /rootfs
        name: root
  volumes:
  - name: root
    hostPath:
      path: /
