apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  hostPID: true
  hostNetwork: true
  containers:
    - name: debug
      image: alpine:3.8
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      env:
      - name: DOCKER_HOST
        value: unix:///rootfs/run/docker.sock
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /rootfs
        name: root
  volumes:
  - name: root
    hostPath:
      path: /
