apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  hostPID: true
  hostNetwork: true
  containers:
    - name: debug
      image: alpine:3.8
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      securityContext:
        privileged: true
