# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "talos-systems/talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.10.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.multi-arch-installer]
        title = "Multi-arch Installer"
        description = """\
Talos installer image (for any arch) now contains artifacts for both `amd64` and `arm64` architecture.
This means that e.g. images for arm64 SBCs can be generated on amd64 host.
"""

    [notes.legacy_bios]
        title = "Legacy BIOS Support"
        description = """\
Added an option to the `machine.install` section of the machine config that can enable marking MBR partition bootable
for the machines that have legacy BIOS which does not support GPT partitioning scheme.
"""

    [notes.coredns]
        title = "CoreDNS"
        description = """\
Added the flag `cluster.coreDNS.disabled` to coreDNS deployment during the cluster bootstrap.
"""

    [notes.components]
        title = "Component Updates"
        description = """\
* containerd was updated to 1.5.2
* Linux kernel was updated to 5.10.29
"""

    [notes.bootstrap]
        title = "Default to Bootstrap workflow"
        description = """\
The `init.yaml` is no longer an output of `talosctl gen config`.
We now encourage using the bootstrap API, instead it `init` node types, as we
intend on deprecating this machine type in the future.
The `init.yaml` and `controlplane.yaml` machine configs are identical with the
exception of the machine type.
Users can use a modified `controlplane.yaml` with the machine type set to
`init` if they would like to avoid using the bootstrap API.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/talos-systems/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/talos-systems/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/talos-systems/extras"
