metadata:
  repository: dianemo/kernel
  variables:
    artifacts: /artifacts
    srcLinux: https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.14.34.tar.xz
pipeline:
  stages:
  - build
stages:
  build:
    tasks:
    - linux
tasks:
  linux:
    template: |
      FROM dianemo/tools:{{ .Docker.Image.Tag}} AS {{ .Docker.CurrentStage }}
      WORKDIR /tools/usr/local/src/{{ .Docker.CurrentStage }}
      RUN curl -L {{ index .Variables "srcLinux" }} | tar --strip-components=1 -xJ
      RUN make mrproper
      COPY src/linux/config .config
      RUN mkdir /tmp
      RUN ln /tools/bin/pwd /bin/pwd
      RUN make -j $(($(nproc) / 2))
      RUN make modules_install INSTALL_MOD_PATH=/tmp
      RUN depmod -b /tmp 4.14.34-dianemo
      RUN cp arch/x86/boot/bzImage /tmp/vmlinuz
      FROM scratch
      COPY --from={{ .Docker.CurrentStage }} /tmp /tmp
