metadata:
  repository: dianemo/conformance
  variables:
    srcKubectl: https://storage.googleapis.com/kubernetes-release/release/v1.12.1/bin/linux/amd64/kubectl
    srcSonobuoy: https://github.com/heptio/sonobuoy/releases/download/v0.12.0/sonobuoy_0.12.0_linux_amd64.tar.gz
pipeline:
  stages:
  - test
stages:
  test:
    tasks:
    - sonobuoy
tasks:
  sonobuoy:
    template: |
      FROM alpine:3.7
      RUN apk --no-cache add curl tar
      RUN curl --retry 3 --retry-delay 60 -L {{ index .Variables "srcKubectl" }} -o /bin/kubectl
      RUN chmod +x /bin/kubectl
      RUN curl --retry 3 --retry-delay 60 -L {{ index .Variables "srcSonobuoy" }} | tar -xz -C /bin
      COPY ./src/sonobuoy.yaml /etc/sonobuoy/sonobuoy.yaml
      ENTRYPOINT ["/bin/sonobuoy"]
      CMD ["run", "--config=/etc/sonobuoy/sonobuoy.yaml"]
