# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  version = "kubernetes-1.11.1"
  name = "k8s.io/api"

[[constraint]]
  version = "kubernetes-1.11.1"
  name = "k8s.io/apimachinery"

[[constraint]]
  version = "kubernetes-1.11.1"
  name = "k8s.io/client-go"

[[constraint]]
  version = "v1.11.1"
  name = "k8s.io/kubernetes"

[[override]]
  version = "1.1.4"
  name = "github.com/json-iterator/go"

[prune]
  go-tests = true
  unused-packages = true
