services:
  init:
    cni: flannel
  kubeadm:
    certificateKey: ChangeMe
    configuration: |
      apiVersion: kubeadm.k8s.io/v1beta1
      kind: InitConfiguration
      bootstrapTokens:
      - token: 1qbsj9.3oz5hsk6grdfp98b
        ttl: 0s
      nodeRegistration:
        name: master-1
        criSocket: /run/containerd/containerd.sock
      localAPIEndpoint:
        advertiseAddress: 10.5.0.6
        bindPort: 6443
      ---
      apiVersion: kubeadm.k8s.io/v1beta1
      kind: ClusterConfiguration
      controlPlaneEndpoint: 10.5.0.6:443
      apiServer:
        certSANs:
        - 127.0.0.1
        - 10.5.0.7
        - 10.5.0.8
      networking:
        dnsDomain: cluster.local
        podSubnet: 10.244.0.1/16
        serviceSubnet: 10.96.0.1/12
      ---
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      featureGates:
        ExperimentalCriticalPodAnnotation: true
  trustd:
    username: 'dev'
    password: 'talos_trust_dev'
    endpoints:
      - 10.5.0.7
      - 10.5.0.8
debug: true
