baseURL = "https://talos.autonomy.io/"
languageCode = "en-us"
title = "Talos"
theme = "autonomy"
sectionPagesMenu = "main"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
    Copyright = "Released under Mozilla Public License 2.0"
    GitHubLink = "https://github.com/autonomy/talos"
    DockerHubLink = "https://hub.docker.com/u/autonomy"

[[menu.main]]
    identifier = "components"
    name       = "Components"
    url        = "/components/"
    weight     = 10

[[menu.main]]
    identifier = "configuration"
    name       = "Configuration"
    url        = "/configuration/"
    weight     = 20

[[menu.main]]
    identifier = "examples"
    name       = "Examples"
    url        = "/examples/"
    weight     = 30
